### ISSUE TITLE
Lua Errors that force you to close game 

### ISSUE THREAD

**Issue by JukeStuff** [BargonMods/FS22_WoodHarvesterControls#1]
![Problem](https://user-images.githubusercontent.com/113805245/191572422-0a7f2a71-6e62-411c-90c4-7a03dd9aca32.png)
I used the new-ish ponsse tractor harvester and after opening the menu it started throwing errors

**Comment by BargonMods** [comment]
Can you try the new release and tell me if that error is fixed? If not please give me more information about it and share the link to the specific harvester your are using.

Thanks!

**Comment by JukeStuff** [comment]
Hey, yes now it works as it should. I was talking about https://www.farming-simulator.com/mod.php?lang=en&country=fi&mod_id=254047&title=fs2022 this one since it seems like a good option for forestry on a budget. Btw great mod :)
