### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by zcaalock** [BargonMods/FS22_WoodHarvesterControls#4]
Is it possible to restrict autoload container to accept wood only when it`s cut? It would be nice to feed wood directly into container, but in vanilla game the whole tree despawn when it hits the tigger

**Comment by BargonMods** [comment]
To do that we need to modify the container script, not the harvester script and as that is part of a DLC it is locked.
Hopefully in FS25 that will be part of the base game and we will be able to modify it.
